export {
  computeRgMod10AlternatingCheckDigit,
  computeRgSpCheckDigit,
  formatRg,
  getRgOfficialSourceUrl,
  getRgUfRules,
  getRgUfSupport,
  isValidRg,
  stripRg,
  validateRg,
  validateRgMg,
  validateRgPr,
  validateRgRj,
  validateRgRs,
  validateRgSc,
  validateRgSp,
  RG_MG_GOLDEN,
  RG_MG_GOLDEN_MASKED,
  RG_MG_GOLDEN_PREFIXED,
  RG_OFFICIAL_SOURCE_URL,
  RG_OFFICIAL_SOURCE_URLS,
  RG_PR_GOLDEN,
  RG_RJ_GOLDEN,
  RG_RJ_GOLDEN_MASKED,
  RG_RS_GOLDEN,
  RG_SC_GOLDEN,
  RG_SP_GOLDEN,
  RG_SP_GOLDEN_MASKED,
  RG_SP_GOLDEN_X,
  RG_SP_GOLDEN_X_MASKED,
  RG_SUPPORTED_UFS,
  RG_UF_RULES,
} from './core/rg/index.js';
export type {
  RgDvAlgorithm,
  RgUfRules,
  RgValidationResult,
  ValidateRgOptions,
} from './core/rg/types.js';
export type { Rg, RgUfCode } from './types/validation-result.js';
