import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const repoRoot = join(packageRoot, '../..');
const sourcePath = join(repoRoot, 'docs/LIBRARY-API.md');
const outputDir = join(packageRoot, 'api');
const outputPath = join(outputDir, 'library-api.md');

const repoBase = 'https://github.com/AlexandreZanata/br-validators/blob/main';

function resolveRepoPath(relativePath: string): string {
  if (relativePath.startsWith('../')) {
    return relativePath.slice(3);
  }
  if (relativePath.startsWith('use-cases/')) {
    return `docs/${relativePath}`;
  }
  if (!relativePath.includes('/')) {
    return `docs/${relativePath}`;
  }
  return relativePath;
}

function rewriteRepoLinks(markdown: string): string {
  return markdown.replace(/\]\((?!https?:\/\/)([^)]+)\)/g, (_match, target: string) => {
    const hashIndex = target.indexOf('#');
    const path = hashIndex >= 0 ? target.slice(0, hashIndex) : target;
    const hash = hashIndex >= 0 ? target.slice(hashIndex) : '';
    return `](${repoBase}/${resolveRepoPath(path)}${hash})`;
  });
}

const source = readFileSync(sourcePath, 'utf8');
const body = rewriteRepoLinks(source);
const synced = `---
title: Library API
description: Auto-synced from docs/LIBRARY-API.md — do not edit this file directly.
editLink: false
lastUpdated: false
---

::: warning Auto-synced
This page is generated by \`pnpm --filter @br-validators/docs sync\` from [\`docs/LIBRARY-API.md\`](https://github.com/AlexandreZanata/br-validators/blob/main/docs/LIBRARY-API.md). Edit the source file in the monorepo.
:::

${body.replace(/^# Library public API contract\s*\n+/m, '# Library public API contract\n\n')}`;

mkdirSync(outputDir, { recursive: true });
writeFileSync(outputPath, synced, 'utf8');
console.log(`Synced ${sourcePath} → ${outputPath}`);
