import { writeFile } from 'node:fs/promises';

import type { SourceHealthState } from './source-health-tracker.js';

const DOC_ACTION =
  'Update docs/OFFICIAL-SOURCES.md and scripts/fetch-*.ts endpoint(s), then run pnpm data:refresh.';

export interface CriticalAlertsPaths {
  markdownPath: string;
  logPath: string;
}

function criticalStates(states: readonly SourceHealthState[]): SourceHealthState[] {
  return states.filter((state) => state.severity === 'critical');
}

export function generateCriticalAlertsMarkdown(
  states: readonly SourceHealthState[],
  updatedAt: string,
): string {
  const critical = criticalStates(states);

  if (critical.length === 0) {
    return [
      '# Critical data source alerts',
      '',
      '> **Maintainers:** scan this file first. Auto-generated by `scripts/data-refresh-bot.ts`.',
      `> Last updated: ${updatedAt}`,
      '',
      `No critical source failures. Last check: ${updatedAt}.`,
      '',
    ].join('\n');
  }

  const lines: string[] = [
    '# Critical data source alerts',
    '',
    '> **Maintainers:** scan this file first. Auto-generated by `scripts/data-refresh-bot.ts`.',
    `> Last updated: ${updatedAt}`,
    '',
    '| Dataset | Endpoints | Severity | Streak (days) | First failure | Embedded data from | Action |',
    '|---------|-----------|----------|---------------|---------------|--------------------|--------|',
  ];

  for (const state of critical) {
    const endpoints = state.endpoints.join(', ') || '—';
    const retained = state.retainedEmbeddedDataFrom ?? 'unknown';
    const firstFailure = state.firstFailureDate ?? '—';
    lines.push(
      `| ${state.datasetId} | ${endpoints} | ${state.severity} | ${String(state.consecutiveFailureDays)} | ${firstFailure} | ${retained} | ${DOC_ACTION} |`,
    );
  }

  lines.push('');
  return `${lines.join('\n')}\n`;
}

export function generateCriticalAlertsLog(
  states: readonly SourceHealthState[],
  updatedAt: string,
): string {
  const critical = criticalStates(states);

  if (critical.length === 0) {
    return `OK no critical alerts last_check=${updatedAt}\n`;
  }

  const lines = critical.map(
    (state) =>
      `CRITICAL dataset=${state.datasetId} streak=${String(state.consecutiveFailureDays)} first_failure=${state.firstFailureDate ?? 'unknown'} retained=${state.retainedEmbeddedDataFrom ?? 'unknown'} message="${state.message}"`,
  );

  lines.push(`UPDATED ${updatedAt}`);
  return `${lines.join('\n')}\n`;
}

export async function writeCriticalAlertsFiles(
  paths: CriticalAlertsPaths,
  states: readonly SourceHealthState[],
  updatedAt: string = new Date().toISOString(),
): Promise<void> {
  await writeFile(paths.markdownPath, generateCriticalAlertsMarkdown(states, updatedAt));
  await writeFile(paths.logPath, generateCriticalAlertsLog(states, updatedAt));
}
